security: 

    password_hashers:
        # auto hasher with default options for the User class (and children)
        App\Entity\User: 'auto'
        # auto hasher with custom options for all PasswordAuthenticatedUserInterface instances
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15
    providers:
        users:
            entity: 
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users
            form_login:
                login_path: login
                check_path: login
            
            logout:
                path: logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 86400
                path:     /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: PUBLIC_ACCESS }
 
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
