security: 
    password_hashers:
        # auto hasher with default options for the User class (and children)
        App\Entity\User: 'auto'

    providers:
        users:
            entity: 
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users
            form_login:
                login_path: login
                check_path: login
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
            logout:
                path: logout
   
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/tasks, roles: ROLE_USER }
