<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIqvAQfq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIqvAQfq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIqvAQfq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIqvAQfq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIqvAQfq\App_KernelDevDebugContainer([
    'container.build_hash' => 'IqvAQfq',
    'container.build_id' => '5bb90505',
    'container.build_time' => 1647859274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIqvAQfq');
