<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xtNZZO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xtNZZO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xtNZZO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xtNZZO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xtNZZO\App_KernelDevDebugContainer([
    'container.build_hash' => '5xtNZZO',
    'container.build_id' => 'e4e430e7',
    'container.build_time' => 1646898546,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xtNZZO');
